name: DEPLOY
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: clean install node modules for production
        run: npm ci --omit=dev
      - name: create .env
        run: |
          echo "NOTION_API_TOKEN=${{ secrets.NOTION_API_TOKEN }}" >> .env
          echo "DISCORD_EVENT_BOT_TOKEN=${{ secrets.DISCORD_EVENT_BOT_TOKEN }}" >> .env
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude=".git" --exclude="wagumi.json"
          path: ./
          remote_path: /home/wagumi/apps/event-tracking-bot
          remote_host: wagumi-prod-jpe-001.japaneast.cloudapp.azure.com
          remote_user: wagumi
          remote_port: 57822
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
